package riv.util;

/*
 * References to cells for use by complete excel report
 */
public enum ExcelLink {
	PROFILE_INVEST_GOODS_RESERVE,
	PROFILE_INVEST_TOTAL,
	PROFILE_INVEST_OWN,
	PROFILE_INVEST_EXTERNAL,
	PROFILE_GENERAL_TOTAL,
	PROFILE_GENERAL_WITHOUT_TOTAL,
	PROFILE_PRODUCT_INCOME,
	PROFILE_PRODUCT_INPUT,
	PROFILE_PRODUCT_LABOUR,
	PROJECT_GENERAL_TOTAL,
	PROJECT_GENERAL_OWN,
	PROJECT_GENERAL_CASH,
	PROJECT_GENERAL_WITHOUT_TOTAL,
	PROJECT_GENERAL_WITHOUT_OWN,
	PROJECT_GENERAL_WITHOUT_CASH,
	PROJECT_INVEST_FINANCED,
	PROJECT_INVEST_FIRSTASSET_SHEET,
	PROJECT_INVEST_FIRSTASSET_ROW,
	PROJECT_LOAN1_AMOUNT,
	PROJECT_LOAN1_GRACE_CAPITAL,
	PROJECT_LOAN1_GRACE_INTEREST,
	PROJECT_LOAN1_DURATION,
	PROJECT_LOAN1_RATE,
	PROJECT_LOAN2_AMOUNT,
	PROJECT_LOAN2_GRACE_CAPITAL,
	PROJECT_LOAN2_GRACE_INTEREST,
	PROJECT_LOAN2_DURATION,
	PROJECT_LOAN2_RATE,
	PROJECT_LOAN2_YEAR,
	PROJECT_WC_FINANCED,
	PROJECT_WC_PERIOD,
	PROJECT_WC_INTEREST,
	PROJECT_INFLATION,
	PROJECT_1ST_YEAR_TOTAL;
}